# Pipeline for ACI changes that contains PCVs.

variables:
  bearer: "ODc5ZDVmZGUtM2Q0Yy00MzM3LTk2YmItYjlhYzZkNTZjN2VmYTk3ZjdlY2ItOTEx_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f"
  roomId: "Y2lzY29zcGFyazovL3VzL1JPT00vYmMzNGIyZjAtNjFmYS0xMWVhLWI4NTgtMTM5NTgxNTJhYmNl"

stages:
  - init-webex
  - verify
  - query
  - build
  - test
  - notify

init-webex:
  stage: init-webex
  script:
    - >-
      curl -H "Content-Type: application/json" -H 'Authorization: Bearer '"$bearer"'' -i -v -X POST -d ' {"roomId": "'"$roomId"'", "text":"
      ###################\nHello Rob, we are kicking off pipeline: '"${CI_PROJECT_NAME}"' - change: #'"${CI_PIPELINE_ID}"'
      "}' https://api.ciscospark.com/v1/messages

create-pcv:
  stage: verify
  script:
    - >-
      curl -H "Content-Type: application/json" -H 'Authorization: Bearer '"$bearer"'' -i -v -X POST -d ' {"roomId": "'"$roomId"'", "text":"
      Starting stage: '"${CI_JOB_STAGE}"' with job ID: '"${CI_JOB_ID}"'
      "}' https://api.ciscospark.com/v1/messages
    - ansible-playbook nae.yaml -i hosts -i inventory -vvv
    - sleep 1

query-pcv:
  stage: query
  script:
    - >-
      curl -H "Content-Type: application/json" -H 'Authorization: Bearer '"$bearer"'' -i -v -X POST -d ' {"roomId": "'"$roomId"'", "text":"
      Starting stage: '"${CI_JOB_STAGE}"' with job ID: '"${CI_JOB_ID}"'
      "}' https://api.ciscospark.com/v1/messages
    - ansible-playbook nae_query.yaml -i hosts -vvv > output_$CI_PIPELINE_ID.txt
  after_script:
    - python3 parser.py

build-aci:
  stage: build
  script:
    - >-
      curl -H "Content-Type: application/json" -H 'Authorization: Bearer '"$bearer"'' -i -v -X POST -d ' {"roomId": "'"$roomId"'", "text":"
      Starting stage: '"${CI_JOB_STAGE}"' with job ID: '"${CI_JOB_ID}"'
      "}' https://api.ciscospark.com/v1/messages
    - ansible-playbook aci.yaml -i hosts

test:
  stage: test
  script:
    - echo "docker test ci run on local mac"

notify_failure:
  stage: notify
  when: on_failure
  script:
    - >-
      curl -H "Content-Type: application/json" -H 'Authorization: Bearer '"$bearer"'' -i -v -X POST -d ' {"roomId": "'"$roomId"'", "text":"
      We have aborted pipeline '"${CI_PIPELINE_URL}"' on branch '"${CI_COMMIT_REF_SLUG}"' \n Please see the report file above for an explanation. \n ################### \n\n
      "}' https://api.ciscospark.com/v1/messages

notify_success:
  stage: notify
  when: on_success
  script:
    - >-
      curl -H "Content-Type: application/json" -H 'Authorization: Bearer '"$bearer"'' -i -v -X POST -d ' {"roomId": "'"$roomId"'", "text":"
      Success on pipeline '"${CI_PIPELINE_URL}"' on branch '"${CI_COMMIT_REF_SLUG}"'\n ################### \n\n
      "}' https://api.ciscospark.com/v1/messages