stages:
  - verify
  - query
  - build
  - test

create-pcv:
  stage: verify
  script:
    - ansible-playbook nae.yaml -i hosts -i inventory -vvv
    - sleep 200

query-pcv:
  stage: query
  script:
    - ansible-playbook nae_query.yaml -i hosts -i inventory -vvv

ansible-aci:
  stage: build
  script:
    - ansible-playbook aci.yaml -i hosts

test:
  stage: test
  script:
    - echo "docker test ci run on local mac"