# Pipeline for ACI changes that contains PCVs and sends info message to WebEx room.

variables:
  bearer: ""
  roomId: ""

stages:
  - init-webex
  - query
  - build
  - test
  - notify

init-webex:
  stage: init-webex
  script:
    - >-
      curl -H "Content-Type: application/json" -H 'Authorization: Bearer '"$bearer"'' -i -v -X POST -d ' {"roomId": "'"$roomId"'", "markdown":"
      ###################\n Hello Rob, we are kicking off pipeline: '"${CI_PROJECT_NAME}"' - change: #'"${CI_PIPELINE_ID}"'
      "}' https://api.ciscospark.com/v1/messages

query:
  stage: query
  before_script:
    - >-
      curl -H "Content-Type: application/json" -H 'Authorization: Bearer '"$bearer"'' -i -v -X POST -d ' {"roomId": "'"$roomId"'", "markdown":"
      Starting stage: '"${CI_JOB_STAGE}"' with job ID: '"${CI_JOB_ID}"'
      "}' https://api.ciscospark.com/v1/messages
  script:
    - ansible-playbook nae.yaml -i hosts -vvv

build-aci:
  stage: build
  before_script:
    - >-
      curl -H "Content-Type: application/json" -H 'Authorization: Bearer '"$bearer"'' -i -v -X POST -d ' {"roomId": "'"$roomId"'", "markdown":"
      Starting stage: '"${CI_JOB_STAGE}"' with job ID: '"${CI_JOB_ID}"'
      "}' https://api.ciscospark.com/v1/messages
  script:
    - ansible-playbook aci.yaml -i hosts

test:
  stage: test
  script:
    - echo "docker test ci run on local mac"

notify_failure:
  stage: notify
  when: on_failure
  script:
    - >-
      curl -H "Content-Type: application/json" -H 'Authorization: Bearer '"$bearer"'' -i -v -X POST -d ' {"roomId": "'"$roomId"'", "markdown":"
      We have aborted pipeline '"${CI_PIPELINE_URL}"' on branch '"${CI_COMMIT_REF_SLUG}"' \n\n The following issues have been found: \n\n
      "}' https://api.ciscospark.com/v1/messages
    - >-
      python3 parser.py

notify_success:
  stage: notify
  when: on_success
  script:
    - >-
      curl -H "Content-Type: application/json" -H 'Authorization: Bearer '"$bearer"'' -i -v -X POST -d ' {"roomId": "'"$roomId"'", "markdown":"
      Success on pipeline '"${CI_PIPELINE_URL}"' on branch '"${CI_COMMIT_REF_SLUG}"'\n ################### \n\n
      "}' https://api.ciscospark.com/v1/messages