- name: NAE pre-change analysis
  hosts: candid-amslab.cisco.com
  connection: local
  gather_facts: no
  vars:
    nae_login: &nae_login
      hostname: candid-amslab.cisco.com
      username: admin
      password: C!sco1234567890
      port: 443
      validate_certs: no
  tasks:
  - name: Add-new Pre-change nalysis by specifying change list manually
    nae_prechange:
        <<: *nae_login
        ag_name: apic-amslab
        name: AddBD_Bla2
        changes: |
            [{
                  "bd_change": {
                     "action": "ADD",
                     "dn": "uni/tn-robvand/BD-BD-2",
                     "optimize_wan_bandwidth": "no",
                     "type": "regular",
                     "arp_flood": "no",
                     "ip_learning": "yes",
                     "limit_ip_learn_to_subnets": "yes",
                     "unk_mac_ucast_act": "proxy",
                     "unicast_route": "yes",
                     "multi_dst_pkt_act": "bd-flood",
                     "unk_mcast_act": "flood",
                     "multi_cast_allow": "no",
                     "vrf_name": "vrf1"
                   }
                 },
                 {
                   "network_subnet_change": {
                     "action": "ADD",
                     "dn": "uni/tn-robvand/BD-BD-3/subnet-10.0.11.1/24",
                     "scope": "private",
                     "make_this_primary_ip_address": "no",
                     "treat_as_virtual_ip_address": "no",
                     "subnet_control": "nd"
                   }
                 }]

        state: present
    delegate_to: localhost