- name: NAE pre-change analysis
  hosts: candid-amslab.cisco.com
  connection: local
  gather_facts: no
  vars:
    nae_login: &nae_login
      hostname: candid-amslab.cisco.com
      username: admin
      password: C!sco1234567890
      port: 443
      validate_certs: no
  tasks:
  - name: Add-new Pre-change analysis by specifying change list manually
    nae_prechange:
        <<: *nae_login
        ag_name: amslab
        name: AddContract
        changes: |
            [{
                  "epg_change": {
                     "action": "MODIFY",
                     "dn": "uni/tn-robvand/ap-sample/epg-frontend",
                     "description": "",
                     "provided_contract_names": [],
                     "consumed_contract_names": ["L3_out_to_common_core"],
                     "taboo_contract_names": [],
                     "pc_enf_pref": "unenforced",
                     "pref_gr_memb": "exclude",
                     "bd_name": "bd-1"
                   }
            }]

        state: present
    delegate_to: localhost

  - name: Query the PCR
    nae_prechange:
      <<: *nae_login
      ag_name: amslab
      name: AddContract
      state: verify
    delegate_to: localhost